// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSa6dvt_Q_TYjJoDJEFWjCp0gbArTpvDc',
    appId: '1:541025586955:web:22cd1a04628f4541e0dc0e',
    messagingSenderId: '541025586955',
    projectId: 'companymanagementsystem-b4e88',
    authDomain: 'companymanagementsystem-b4e88.firebaseapp.com',
    storageBucket: 'companymanagementsystem-b4e88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQcYp8xkx0oVgkeZ44ukM9p_pOqN-edD4',
    appId: '1:541025586955:android:1ab459a283991e51e0dc0e',
    messagingSenderId: '541025586955',
    projectId: 'companymanagementsystem-b4e88',
    storageBucket: 'companymanagementsystem-b4e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQgVLviXp9nRATnNfWjqLE5tSaLAqJ4vk',
    appId: '1:541025586955:ios:e3d3d22d732cdb4de0dc0e',
    messagingSenderId: '541025586955',
    projectId: 'companymanagementsystem-b4e88',
    storageBucket: 'companymanagementsystem-b4e88.firebasestorage.app',
    iosBundleId: 'com.company.companyManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSa6dvt_Q_TYjJoDJEFWjCp0gbArTpvDc',
    appId: '1:541025586955:web:807ed72d03e45a78e0dc0e',
    messagingSenderId: '541025586955',
    projectId: 'companymanagementsystem-b4e88',
    authDomain: 'companymanagementsystem-b4e88.firebaseapp.com',
    storageBucket: 'companymanagementsystem-b4e88.firebasestorage.app',
  );
}
