// Helpers for accounts that sign in with a username instead of a real
// email. Firebase Authentication only understands email + password, so a
// username-based login is created behind the scenes as
// "<username>@<kInternalAuthDomain>" — this file is the single place
// that knows about that convention, so the rest of the app never has to
// guess whether an email is a real one or a synthetic one.

/// The fake domain used for username-only accounts. Never actually
/// resolves to a mail server — Firebase just needs *some* valid-looking
/// email format to create the account.
const String kInternalAuthDomain = 'members.internal.app';

/// Builds the internal Firebase Auth email for a given username.
/// e.g. internalEmailFor('hassan123') -> 'hassan123@members.internal.app'
String internalEmailFor(String username) {
  final normalized = username.trim().toLowerCase().replaceAll(' ', '_');
  return '$normalized@$kInternalAuthDomain';
}

/// True if [email] was generated by [internalEmailFor] rather than being
/// a real address someone can receive mail at.
bool isInternalAuthEmail(String email) {
  return email.trim().toLowerCase().endsWith('@$kInternalAuthDomain');
}

/// What to show in the UI instead of the raw email/uid. For an internal
/// (username-based) account this is just the username part. For a real
/// email, it falls back to the part before the "@" so something readable
/// is always shown even if no separate username was ever set.
String displayUsername(String email) {
  if (email.isEmpty) return '';
  if (isInternalAuthEmail(email)) {
    return email.split('@').first;
  }
  return email.contains('@') ? email.split('@').first : email;
}